name: Compile

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - run: npm install typescript
    - name: npm building
      run: tsc -b .\Decorator
    - name: npm build
      run: npm run build
